<a href="https://colab.research.google.com/github/Kevinsamuelgitau/W9-IP/blob/master/SAM_GITAU_W9_IP_NOTEBOOK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DEFINING THE ANALYTIC QUESTION

# a. SPECIFYING THE ANALYTIC QUESTION

Our task is to create a model that predicts whether an email is a spam or not based on the texts it contains

# b. DEFINING METRICS FOR SUCCESS

Our metrics for successs are achieving a highly accurate model without overfitting or underfitting

# c. UNDERSTANDING THE CONTEXT

Our task is to study the dataset, clean it and later create models that predict whether an email is a spam or not

# d. RECORDING THE EXPERIMANTAL DESIGN

Here is the exepected workflow of our project:
1. Importing relevant libraries
2. Checking the dataset
3. Tidying the dataset
4. Implementing the solution
5. Model optimization
6. Follow up questions

# e. DATA RELEVANCE

Data Set Information:
Here is a link to the dataset: https://archive.ics.uci.edu/ml/datasets/Spambase

The "spam" concept is diverse: advertisements for products/web sites, make money fast schemes, chain letters, pornography...

Our collection of spam e-mails came from our postmaster and individuals who had filed spam. Our collection of non-spam e-mails came from filed work and personal e-mails, and hence the word 'george' and the area code '650' are indicators of non-spam. These are useful when constructing a personalized spam filter. One would either have to blind such non-spam indicators or get a very wide collection of non-spam to generate a general purpose spam filter.

The last column of 'spambase.data' denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail. Most of the attributes indicate whether a particular word or character was frequently occuring in the e-mail. The run-length attributes (55-57) measure the length of sequences of consecutive capital letters

# IMPORTING LIBRARIES

In [1]:
# Importing all libraries required for analysis
import pandas as pd
import sklearn.model_selection as ms
from sklearn import linear_model
import sklearn.metrics as sklm
import numpy as np
import numpy.random as nr
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss
import math

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

# LOADING THE DATASET

In [2]:
# Loading the dataset and previewing the first records
df= pd.read_csv('spambasedata.csv')
df.head()

   word_freq_make  word_freq_address  ...  capital_run_length_total  class
0            0.00               0.64  ...                    1028.0    1.0
1            0.21               0.28  ...                    2259.0    1.0
2            0.06               0.00  ...                     191.0    1.0
3            0.00               0.00  ...                     191.0    1.0
4            0.00               0.00  ...                      54.0    1.0

[5 rows x 58 columns]

In [3]:
# previewing the last records
df.tail()

      word_freq_make  word_freq_address  ...  capital_run_length_total  class
4596            0.31                0.0  ...                      14.0    0.0
4597            0.00                0.0  ...                     118.0    0.0
4598            0.30                0.0  ...                      78.0    0.0
4599            0.96                0.0  ...                      40.0    0.0
4600            0.00                0.0  ...                       NaN    NaN

[5 rows x 58 columns]

# CHECKING THE DATA

In [4]:
# checking for number of records
df.shape

(4601, 58)

In [5]:
# checking datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 non-null   float64
 14  word_freq_addresses         4601 non-null   float64
 15  word_freq_free              4601 non-null   float64
 16  word_freq_business          4601 non-null   float64
 17  word_freq_email             4601 non-null   float64
 18  word_freq_you               4601 non-null   float64
 19  word_freq_credit            4601 non-null   float64
 20  word_freq_your              4600 non-null   float64
 21  word_freq_font              4600 non-null   float64
 22  word_freq_000               4600 non-null   float64
 23  word_freq_money             4600 non-null   float64
 24  word_freq_hp                4600 non-null   float64
 25  word_freq_hpl               4600 non-null   float64
 26  word_freq_george            4600 non-null   float64
 27  word_freq_650               4600 non-null   float64
 28  word_freq_lab               4600 non-null   float64
 29  word_freq_labs              4600 non-null   float64
 30  word_freq_telnet            4600 non-null   float64
 31  word_freq_857               4600 non-null   float64
 32  word_freq_data              4600 non-null   float64
 33  word_freq_415               4600 non-null   float64
 34  word_freq_85                4600 non-null   float64
 35  word_freq_technology        4600 non-null   float64
 36  word_freq_1999              4600 non-null   float64
 37  word_freq_parts             4600 non-null   float64
 38  word_freq_pm                4600 non-null   float64
 39  word_freq_direct            4600 non-null   float64
 40  word_freq_cs                4600 non-null   float64
 41  word_freq_meeting           4600 non-null   float64
 42  word_freq_original          4600 non-null   float64
 43  word_freq_project           4600 non-null   float64
 44  word_freq_re                4600 non-null   float64
 45  word_freq_edu               4600 non-null   float64
 46  word_freq_table             4600 non-null   float64
 47  word_freq_conference        4600 non-null   float64
 48  char_freq_;                 4600 non-null   float64
 49  char_freq_(                 4600 non-null   float64
 50  char_freq_[                 4600 non-null   float64
 51  char_freq_!                 4600 non-null   float64
 52  char_freq_$                 4600 non-null   float64
 53  char_freq_#                 4600 non-null   float64
 54  capital_run_length_average  4600 non-null   float64
 55  capital_run_length_longest  4600 non-null   float64
 56  capital_run_length_total    4600 non-null   float64
 57  class                       4600 non-null   float64
dtypes: float64(58)
memory usage: 2.0 MB

In [6]:
# checking statistics
df.describe()

       word_freq_make  word_freq_address  ...  capital_run_length_total        class
count     4601.000000        4601.000000  ...               4600.000000  4600.000000
mean         0.104553           0.213015  ...                283.290435     0.393913
std          0.305358           1.290575  ...                606.413764     0.488669
min          0.000000           0.000000  ...                  1.000000     0.000000
25%          0.000000           0.000000  ...                 35.000000     0.000000
50%          0.000000           0.000000  ...                 95.000000     0.000000
75%          0.000000           0.000000  ...                265.250000     1.000000
max          4.540000          14.280000  ...              15841.000000     1.000000

[8 rows x 58 columns]

# TIDYING THE DATASET

In [7]:
# checking for missing values
df.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                1
word_freq_font                1
word_freq_000                 1
word_freq_money               1
word_freq_hp                  1
word_freq_hpl                 1
word_freq_george              1
word_freq_650                 1
word_freq_lab                 1
word_freq_labs                1
word_freq_telnet              1
word_freq_857                 1
word_freq_data                1
word_freq_415                 1
word_freq_85                  1
word_freq_technology          1
word_freq_1999                1
word_freq_parts               1
word_freq_pm                  1
word_freq_direct              1
word_freq_cs                  1
word_freq_meeting             1
word_freq_original            1
word_freq_project             1
word_freq_re                  1
word_freq_edu                 1
word_freq_table               1
word_freq_conference          1
char_freq_;                   1
char_freq_(                   1
char_freq_[                   1
char_freq_!                   1
char_freq_$                   1
char_freq_#                   1
capital_run_length_average    1
capital_run_length_longest    1
capital_run_length_total      1
class                         1
dtype: int64

In [8]:
# Drop  null values from the dataset
# shape before droping the null values
print(df.shape)

# Droping null values
df_new =df.dropna()

#shape of the new dataset
df_new.shape

(4601, 58)

(4600, 58)

In [9]:
# Remove duplicated values

df_new.drop_duplicates().all()

word_freq_make                False
word_freq_address             False
word_freq_all                 False
word_freq_3d                  False
word_freq_our                 False
word_freq_over                False
word_freq_remove              False
word_freq_internet            False
word_freq_order               False
word_freq_mail                False
word_freq_receive             False
word_freq_will                False
word_freq_people              False
word_freq_report              False
word_freq_addresses           False
word_freq_free                False
word_freq_business            False
word_freq_email               False
word_freq_you                 False
word_freq_credit              False
word_freq_your                False
word_freq_font                False
word_freq_000                 False
word_freq_money               False
word_freq_hp                  False
word_freq_hpl                 False
word_freq_george              False
word_freq_650                 False
word_freq_lab                 False
word_freq_labs                False
word_freq_telnet              False
word_freq_857                 False
word_freq_data                False
word_freq_415                 False
word_freq_85                  False
word_freq_technology          False
word_freq_1999                False
word_freq_parts               False
word_freq_pm                  False
word_freq_direct              False
word_freq_cs                  False
word_freq_meeting             False
word_freq_original            False
word_freq_project             False
word_freq_re                  False
word_freq_edu                 False
word_freq_table               False
word_freq_conference          False
char_freq_;                   False
char_freq_(                   False
char_freq_[                   False
char_freq_!                   False
char_freq_$                   False
char_freq_#                   False
capital_run_length_average     True
capital_run_length_longest     True
capital_run_length_total       True
class                         False
dtype: bool

In [10]:
# to remove white spaces from our columns

df_new.columns = df_new.columns.str.strip().str.replace('','').str.lower()
df_new.columns

Index(['word_freq_make', 'word_freq_address', 'word_freq_all', 'word_freq_3d',
       'word_freq_our', 'word_freq_over', 'word_freq_remove',
       'word_freq_internet', 'word_freq_order', 'word_freq_mail',
       'word_freq_receive', 'word_freq_will', 'word_freq_people',
       'word_freq_report', 'word_freq_addresses', 'word_freq_free',
       'word_freq_business', 'word_freq_email', 'word_freq_you',
       'word_freq_credit', 'word_freq_your', 'word_freq_font', 'word_freq_000',
       'word_freq_money', 'word_freq_hp', 'word_freq_hpl', 'word_freq_george',
       'word_freq_650', 'word_freq_lab', 'word_freq_labs', 'word_freq_telnet',
       'word_freq_857', 'word_freq_data', 'word_freq_415', 'word_freq_85',
       'word_freq_technology', 'word_freq_1999', 'word_freq_parts',
       'word_freq_pm', 'word_freq_direct', 'word_freq_cs', 'word_freq_meeting',
       'word_freq_original', 'word_freq_project', 'word_freq_re',
       'word_freq_edu', 'word_freq_table', 'word_freq_conference',
       'char_freq_;', 'char_freq_(', 'char_freq_[', 'char_freq_!',
       'char_freq_$', 'char_freq_#', 'capital_run_length_average',
       'capital_run_length_longest', 'capital_run_length_total', 'class'],
      dtype='object')

In [11]:
# Check for outliers through IQR Score

# we first get the interquantile range for each column
Q1 = df_new.quantile(0.25)
Q3 = df_new.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

word_freq_make                  0.00000
word_freq_address               0.00000
word_freq_all                   0.42000
word_freq_3d                    0.00000
word_freq_our                   0.38250
word_freq_over                  0.00000
word_freq_remove                0.00000
word_freq_internet              0.00000
word_freq_order                 0.00000
word_freq_mail                  0.16000
word_freq_receive               0.00000
word_freq_will                  0.80000
word_freq_people                0.00000
word_freq_report                0.00000
word_freq_addresses             0.00000
word_freq_free                  0.10000
word_freq_business              0.00000
word_freq_email                 0.00000
word_freq_you                   2.64000
word_freq_credit                0.00000
word_freq_your                  1.27000
word_freq_font                  0.00000
word_freq_000                   0.00000
word_freq_money                 0.00000
word_freq_hp                    0.00000
word_freq_hpl                   0.00000
word_freq_george                0.00000
word_freq_650                   0.00000
word_freq_lab                   0.00000
word_freq_labs                  0.00000
word_freq_telnet                0.00000
word_freq_857                   0.00000
word_freq_data                  0.00000
word_freq_415                   0.00000
word_freq_85                    0.00000
word_freq_technology            0.00000
word_freq_1999                  0.00000
word_freq_parts                 0.00000
word_freq_pm                    0.00000
word_freq_direct                0.00000
word_freq_cs                    0.00000
word_freq_meeting               0.00000
word_freq_original              0.00000
word_freq_project               0.00000
word_freq_re                    0.11000
word_freq_edu                   0.00000
word_freq_table                 0.00000
word_freq_conference            0.00000
char_freq_;                     0.00000
char_freq_(                     0.18800
char_freq_[                     0.00000
char_freq_!                     0.31425
char_freq_$                     0.05200
char_freq_#                     0.00000
capital_run_length_average      2.11725
capital_run_length_longest     37.00000
capital_run_length_total      230.25000
class                           1.00000
dtype: float64

In [12]:
# We then get the outliers as follows:
# True means presence of outliers

(df_new < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))

      word_freq_make  word_freq_address  ...  capital_run_length_total  class
0              False               True  ...                      True  False
1               True               True  ...                      True  False
2               True              False  ...                     False  False
3              False              False  ...                     False  False
4              False              False  ...                     False  False
...              ...                ...  ...                       ...    ...
4596            True              False  ...                     False  False
4597           False              False  ...                     False  False
4598            True              False  ...                     False  False
4599            True              False  ...                     False  False
4600           False              False  ...                     False  False

[4601 rows x 58 columns]

In [13]:
# We then filter out outliers and remain with valid values as follows

df_clean = df_new[~((df_new < (Q1 - 1.5 * IQR)) |(df_new > (Q3 + 1.5 * IQR))).any(axis=1)]
df_clean.shape

(138, 58)

Removing outliers will significantly reduce the number of records, so we will work with the data without removing outliers

In [14]:
df_new.shape

(4600, 58)

# IMPLEMENTING THE SOLUTION

80 - 20  sets

In [15]:
# Load libraries and datasets to be used in this example
#
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [17]:
X = df_new.drop(['class'], 1)
y = df_new['class']

In [29]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [31]:
# Predicting our test predictors
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8152173913043478

In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# Evaluating the Algorithm
# The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[431  99]
 [118 272]]
              precision    recall  f1-score   support

         0.0       0.79      0.81      0.80       530
         1.0       0.73      0.70      0.71       390

    accuracy                           0.76       920
   macro avg       0.76      0.76      0.76       920
weighted avg       0.76      0.76      0.76       920

70-30 set

In [33]:

X = df_new.drop(['class'], 1)
y = df_new['class']

In [36]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [37]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [38]:
# Predicting our test predictors
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8166666666666667

In [39]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# Evaluating the Algorithm
# The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[648 155]
 [167 410]]
              precision    recall  f1-score   support

         0.0       0.80      0.81      0.80       803
         1.0       0.73      0.71      0.72       577

    accuracy                           0.77      1380
   macro avg       0.76      0.76      0.76      1380
weighted avg       0.77      0.77      0.77      1380

60-40 set

In [40]:
X = df_new.drop(['class'], 1)
y = df_new['class']

In [41]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [42]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [43]:
# Predicting our test predictors
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8092391304347826

In [44]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# Evaluating the Algorithm
# The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[861 228]
 [207 544]]
              precision    recall  f1-score   support

         0.0       0.81      0.79      0.80      1089
         1.0       0.70      0.72      0.71       751

    accuracy                           0.76      1840
   macro avg       0.76      0.76      0.76      1840
weighted avg       0.76      0.76      0.76      1840

Using normalization

In [45]:
# Load libraries
from sklearn.preprocessing import Normalizer
import numpy as np

In [46]:
X = df_new.drop(['class'], 1)
y = df_new['class']

In [47]:
# Create normalizer
normalizer = Normalizer(norm='l2')

# Transform feature matrix
normalizer.transform(X)

array([[0.00000000e+00, 6.19574416e-04, 6.19574416e-04, ...,
        4.95078682e-03, 9.77765876e-02, 9.95191406e-01],
       [9.08893441e-05, 1.21185792e-04, 2.16403200e-04, ...,
        4.25059166e-03, 2.09911104e-01, 9.77709658e-01],
       [3.07378553e-04, 0.00000000e+00, 3.63731288e-03, ...,
        1.81199657e-02, 2.04919035e-01, 9.78488393e-01],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.18659542e-02, 5.07092061e-02, 9.97281054e-01],
       [3.83570373e-03, 0.00000000e+00, 3.83570373e-03, ...,
        1.46651739e-02, 6.39283955e-02, 9.97282969e-01],
       [2.37333459e-02, 0.00000000e+00, 0.00000000e+00, ...,
        3.09027941e-02, 1.23611176e-01, 9.88889410e-01]])

In [48]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [50]:
# Predicting our test predictors
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8152173913043478

In [51]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# Evaluating the Algorithm
# The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[431  99]
 [118 272]]
              precision    recall  f1-score   support

         0.0       0.79      0.81      0.80       530
         1.0       0.73      0.70      0.71       390

    accuracy                           0.76       920
   macro avg       0.76      0.76      0.76       920
weighted avg       0.76      0.76      0.76       920

Applying smoothing techniques

In [52]:
rng = np.random.RandomState(1)
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)
MultinomialNB()

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [53]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [54]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [55]:
# Predicting our test predictors
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8152173913043478

In [56]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# Evaluating the Algorithm
# The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[431  99]
 [118 272]]
              precision    recall  f1-score   support

         0.0       0.79      0.81      0.80       530
         1.0       0.73      0.70      0.71       390

    accuracy                           0.76       920
   macro avg       0.76      0.76      0.76       920
weighted avg       0.76      0.76      0.76       920